name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Get Node.js version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build artifacts
        run: |
          yarn build:prod:zip:chrome
          yarn build:prod:zip:edge
          yarn build:prod:zip:firefox
          yarn build:prod:zip:opera
          ENABLE_CONTRIBUTIONS=false yarn build:prod:zip:safari
          ENABLE_CONTRIBUTIONS=false yarn build:prod:zip:samsung
      - name: Hash artifacts
        run: sha256sum artifacts/*/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: artifacts
          path: artifacts/
          retention-days: 1
  release:
    name: Release on GitHub
    runs-on: ubuntu-20.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Get release information
        id: release_info
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts/
      - name: Hash artifacts
        run: sha256sum artifacts/*/*
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.TAG }}
          name: ${{ steps.release_info.outputs.TAG }}
          body: |
            Download and install the extension from the [extension store](https://github.com/dessant/search-by-image#readme) of your browser.

            Learn more about this release from the [changelog](https://github.com/dessant/search-by-image/blob/master/CHANGELOG.md#changelog).
          files: artifacts/*/*
          fail_on_unmatched_files: true
          draft: true
